# This case study consists of 1000 marks and the solution file is expected to be submitted in the upcoming session for evaluation.

In [1]:
import numpy as np

### 1.Create two matrices of 3*3 and perform the arithmatic operations metioned in below "print" statements

In [2]:
mat1 = np.random.randint(0,9,size=(3,3))
mat2 = np.random.randint(0,9,size=(3,3))
print("\n1st Matrix of random single-digit numbers\n----------------------------------------\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n----------------------------------------\n",mat2)


print("\nAddition\n------------------\n", mat1 + mat2)
print("\nMultiplication\n------------------\n", mat1 * mat2)


print("\nDivision\n------------------\n", mat1 / mat2)
print("\nLinear combination: 3*A - 2*B\n-----------------------------\n", 3 * mat1 - 2* mat2)


print("\nAddition of a scalar (100)\n-------------------------\n", mat1 +100)


print("\nExponentiation, matrix cubed here\n----------------------------------------\n", mat1 **3)
print("\nExponentiation, mat1 sq-root using pow function\n-------------------------------------------\n",pow(mat1,0.5) )


1st Matrix of random single-digit numbers
----------------------------------------
 [[2 8 5]
 [6 2 5]
 [2 1 6]]

2nd Matrix of random single-digit numbers
----------------------------------------
 [[7 8 4]
 [1 1 4]
 [6 8 4]]

Addition
------------------
 [[ 9 16  9]
 [ 7  3  9]
 [ 8  9 10]]

Multiplication
------------------
 [[14 64 20]
 [ 6  2 20]
 [12  8 24]]

Division
------------------
 [[0.28571429 1.         1.25      ]
 [6.         2.         1.25      ]
 [0.33333333 0.125      1.5       ]]

Linear combination: 3*A - 2*B
-----------------------------
 [[ -8   8   7]
 [ 16   4   7]
 [ -6 -13  10]]

Addition of a scalar (100)
-------------------------
 [[102 108 105]
 [106 102 105]
 [102 101 106]]

Exponentiation, matrix cubed here
----------------------------------------
 [[  8 512 125]
 [216   8 125]
 [  8   1 216]]

Exponentiation, mat1 sq-root using pow function
-------------------------------------------
 [[1.41421356 2.82842712 2.23606798]
 [2.44948974 1.41421356 2.2360679

Some operations, such as += and *=, act in place to modify an existing array rather than create a new one.

NumPy provides familiar mathematical functions such as sin, cos, and exp. In NumPy, these are called “universal functions”(ufunc). Within NumPy, these functions operate elementwise on an array, producing an array as output.

### 2.Create two 3 * 3 matrices and perform the following operations as describe in print statement.

In [3]:
from numpy.random import randint as ri
mat1 = ri(0,9,size=(3,3))
mat2 = ri(0,9,size=(3,3))
print("\n1st Matrix of random single-digit numbers\n","-"*50,"\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n","-"*50,"\n",mat2)


print("\nSum of all numbers in 1st matrix\n","-"*50,"\n",np.sum(mat1))
print("\nSum of all numbers in columns of 1st matrix\n","-"*50,"\n",np.sum(mat1,axis=0))


print("\nSum of all numbers in rows of 1st matrix\n","-"*50,"\n",np.sum(mat1, axis=1))
print("\nProduct of all numbers in rows of 1st matrix\n","-"*50,"\n",np.prod(mat1, axis=1))


print("\nProduct of all numbers in columns of 2nd matrix\n","-"*50,"\n",np.prod(mat2, axis=0))
print("\nMean of all numbers in 1st matrix\n","-"*50,"\n", np.mean(mat1))


print("\nStandard deviation of all numbers in 1st matrix\n","-"*50,"\n", np.std(mat1))


mat1 = ri(0,100,size=(3,3))
print("\nModified matrix of random numbers from 1 to 99\n","-"*50,"\n",mat1)


print("\nStandard deviation of all numbers in the modified matrix, a larger number\n","-"*80,"\n",np.std(mat1))


print("\nVariance of all numbers in the modified matrix, a larger number\n","-"*80,"\n",np.var(mat1))


print("\nMedian of all numbers in the modified matrix\n","-"*60,"\n",np.median(mat1))


1st Matrix of random single-digit numbers
 -------------------------------------------------- 
 [[4 3 0]
 [1 7 0]
 [6 8 7]]

2nd Matrix of random single-digit numbers
 -------------------------------------------------- 
 [[0 7 5]
 [2 5 2]
 [0 7 1]]

Sum of all numbers in 1st matrix
 -------------------------------------------------- 
 36

Sum of all numbers in columns of 1st matrix
 -------------------------------------------------- 
 [11 18  7]

Sum of all numbers in rows of 1st matrix
 -------------------------------------------------- 
 [ 7  8 21]

Product of all numbers in rows of 1st matrix
 -------------------------------------------------- 
 [  0   0 336]

Product of all numbers in columns of 2nd matrix
 -------------------------------------------------- 
 [  0 245  10]

Mean of all numbers in 1st matrix
 -------------------------------------------------- 
 4.0

Standard deviation of all numbers in 1st matrix
 -------------------------------------------------- 
 2.9814239699997

###  3.Create a 3 \* 3 Matrix and Modify its shape to 9\*1 matrix.

In [4]:
##Solution
mat = ri(0,9,size=(3,3))
print("3*3 matrix is\n {}".format(mat))
mat = mat.reshape(9,1)
print("modified matrix is {}".format(mat))

3*3 matrix is
 [[6 6 6]
 [0 1 4]
 [2 2 3]]
modified matrix is [[6]
 [6]
 [6]
 [0]
 [1]
 [4]
 [2]
 [2]
 [3]]


### 4.Sort

In [6]:
A = ri(0,9,size=(3,3)) # Vector of random interegrs
print("\nVector of 10 random integers from 1 to 100\n",'-'*50,"\n",A)
print("\nHere is the sorted vector in each row\n",'-'*50,"\n",np.sort(A))



Vector of 10 random integers from 1 to 100
 -------------------------------------------------- 
 [[3 3 0]
 [7 5 3]
 [0 2 2]]

Here is the sorted vector in each row
 -------------------------------------------------- 
 [[0 3 3]
 [3 5 7]
 [0 2 2]]


In [7]:
M = ri(0,9,size=(5,5)) #  5*5 Matrix of random interegrs
print("\n5x5 Matrix of random integers\n",'-'*50,"\n",M)
print("\nHere is the sorted matrix along each row\n",'-'*50,"\n",np.sort(M)) # Default axis =1
print("\nHere is the sorted matrix along each column\n",'-'*50,"\n",np.sort(M, axis=0))


5x5 Matrix of random integers
 -------------------------------------------------- 
 [[3 2 8 0 8]
 [2 4 4 8 7]
 [2 3 5 4 0]
 [8 7 4 5 1]
 [5 5 5 6 4]]

Here is the sorted matrix along each row
 -------------------------------------------------- 
 [[0 2 3 8 8]
 [2 4 4 7 8]
 [0 2 3 4 5]
 [1 4 5 7 8]
 [4 5 5 5 6]]

Here is the sorted matrix along each column
 -------------------------------------------------- 
 [[2 2 4 0 0]
 [2 3 4 4 1]
 [3 4 5 5 4]
 [5 5 5 6 7]
 [8 7 8 8 8]]


### 5.Create a,b,c  10 element vectors of random integers and perform the respective operation mentioned in print statement

In [8]:
# Fill the following ***** with appropriate solution.
a=ri(0,9,size=(1,10))
b=ri(0,9,size=(1,10))
c=ri(0,9,size=(1,10))

print("a:", a)
print("b:", b)
print("c:", c)

print("Max of a:", np.max(a))
print("Max of b:",np.max(b))


print("Max of a location:", np.argmax(a))
print("Max of b location:", np.argmax(b))
print("Max of c location:", np.argmax(c))

a: [[4 5 3 0 7 3 4 0 3 5]]
b: [[1 5 0 1 1 0 2 0 0 1]]
c: [[1 0 4 4 2 5 0 5 7 7]]
Max of a: 7
Max of b: 5
Max of a location: 4
Max of b location: 1
Max of c location: 8


## Universal functions

6. Create 3*3 matrices of random single-digit numbers.<br/>
Apply universal functions on it. (square root,exponetial,log10,Modulo etc.)

In [9]:
mat1 = ri(0,9,size=(3,3))
mat2 = ri(0,9,size=(3,3))
print("\n1st Matrix of random single-digit numbers\n----------------------------------------\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n----------------------------------------\n",mat2)


print("\nSq-root of 1st matrix using np\n------------------\n", np.sqrt(mat1))


print("\nExponential power of 1st matrix using np\n",'-'*50,"\n", np.exp(mat1))


print("\n10-base logarithm on 1st matrix using np\n",'-'*50,"\n", np.log10(mat1))


print("\nModulo reminder using np\n",'-'*50,"\n", np.mod(mat1,2))


1st Matrix of random single-digit numbers
----------------------------------------
 [[5 5 5]
 [1 1 8]
 [3 0 6]]

2nd Matrix of random single-digit numbers
----------------------------------------
 [[0 5 7]
 [8 4 7]
 [3 4 2]]

Sq-root of 1st matrix using np
------------------
 [[2.23606798 2.23606798 2.23606798]
 [1.         1.         2.82842712]
 [1.73205081 0.         2.44948974]]

Exponential power of 1st matrix using np
 -------------------------------------------------- 
 [[1.48413159e+02 1.48413159e+02 1.48413159e+02]
 [2.71828183e+00 2.71828183e+00 2.98095799e+03]
 [2.00855369e+01 1.00000000e+00 4.03428793e+02]]

10-base logarithm on 1st matrix using np
 -------------------------------------------------- 
 [[0.69897    0.69897    0.69897   ]
 [0.         0.         0.90308999]
 [0.47712125       -inf 0.77815125]]

Modulo reminder using np
 -------------------------------------------------- 
 [[1 1 1]
 [1 1 0]
 [1 0 0]]


C:\Users\Anu\Anaconda3\lib\site-packages\ipykernel_launcher.py:13: RuntimeWarning: divide by zero encountered in log10
  del sys.path[0]


### 7.Generating matrices from distributions

In [10]:
print("Random number generation (from Uniform distribution)")
print(np.random.uniform(0,1,size=(2,3))) # 2 by 3 matrix with random numbers ranging from 0 to 1, Note no Tuple is necessary 

print("Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal")
print(np.random.randn(3,3))

print("Random integer vector:",np.random.randint(1,100,10)) #randint (low, high, # of samples to be drawn)
print ("\nRandom integer matrix")
print(np.random.randint(1,100,10).reshape(5*2)) #randint (low, high, # of samples to be drawn in a tuple to form a matrix)

print("\n20 samples drawn from a dice throw:", np.random.randint(1,7,20) )# 20 samples drawn from a dice throw

Random number generation (from Uniform distribution)
[[0.51039823 0.27087935 0.8736215 ]
 [0.95400823 0.26204288 0.28489305]]
Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal
[[-0.50168259  0.15565309  0.13505701]
 [-0.11360027 -0.73384526 -1.77821796]
 [ 1.84583153 -1.19604154 -0.88199374]]
Random integer vector: [89 40  7 35 89 61 95 73 99 20]

Random integer matrix
[18 90 97 45 52 22 87 52 72 80]

20 samples drawn from a dice throw: [5 3 1 2 2 1 6 5 5 1 3 1 2 6 5 3 3 6 3 3]


### 8.Find the nearest value from a given number in an array using NumPy.

In [11]:
#Steps
#Create an array of 5 random element from 1 to 12
mat = np.random.randint(1,13,5)
#Suppose find the nearest values of 10 in an array so set value=10
value =10
#find the index where difference is minimum and get the element
print("matrix is {}".format(mat))
print("value is {}".format(value))
diff= np.absolute(mat-value)
print ("Nearest number is {}".format(mat[np.argmin(diff)]))

matrix is [ 3  7  9  5 10]
value is 10
Nearest number is 10


### 9.Write code using numpy to produce following output
[[0 0 0] [0 1 2] [0 2 4]]

In [12]:
[[i*j for i in range(0,3)] for j in range(0,3)]

[[0, 0, 0], [0, 1, 2], [0, 2, 4]]